### ISSUE TITLE
Clicking 'Create Email Alert' gives no feedback on error

### ISSUE THREAD

**Issue by kumarharsh** [labnol/covid19-vaccine-tracker#2]
I'm consistently getting an error:

```
)]}'

[["op.exec",null,[2,[]
,"We're sorry, a server error occurred while reading from storage. Error code PERMISSION_DENIED.","ScriptError"]
]
,["di",444,null,null,null,null,[]
,[]
,null,null,[]
,[]
,[]
]
]
```

For the request(s):
```
["init","[{\"pincode\":\"226001\",\"email\":\"<redacted>\",\"frequency\":\"2\",\"young\":true,\"old\":false}]",null,[0],null,null,true,0]
```

Any PIN code from Lucknow is giving the error.

**Comment by labnol** [comment]
Are you logged into multiple Google accounts in the same browser? Google add-ons may sometimes display an error when multiple accounts are authorized in the same browser session.

Let's see if this workaround solves the issue.

Open Google Chrome, go to the menu and choose New Incognito Window. Here open the same Google Sheet and try again. Let me know if that resolves the issue?

**Comment by labnol** [comment]
Resolved in the latest release.
