### ISSUE TITLE
CDN API is returning 403 error code.

### ISSUE THREAD

**Issue by thunkWaltz** [labnol/covid19-vaccine-tracker#5]
Getting following error with response code 403

HTTP Output = <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: yaPSSJzUvDS5TF06LGBzHqc43V_VZkPAX8zVdX0KQnW12QD4bAcBbA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

Do I need some authentication headers? API is working fine from local host though.

**Comment by zaid-shaikh** [comment]
Yes, I am facing the same issue since today afternoon

**Comment by sidchh91** [comment]
```
[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: hCGCME-KFVmCkXCoQb6rb7jvBh6EE9p3iVvv6H15TGF6W9td9IUoQQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>]
```

Looks like Cloudfront is blocking all requests from Google services

**Comment by sixfooter** [comment]
>>Looks like their Cloudfront config is blocking all requests from Google services

would that mean that using unix to launch this would still work?

**Comment by labnol** [comment]
This is resolved. See [tweet](https://twitter.com/labnol/status/1390255208408641539).

**Comment by akshay6690** [comment]
> ```
> 
> [<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
> 
> <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
> 
> <TITLE>ERROR: The request could not be satisfied</TITLE>
> 
> </HEAD><BODY>
> 
> <H1>403 ERROR</H1>
> 
> <H2>The request could not be satisfied.</H2>
> 
> <HR noshade size="1px">
> 
> Request blocked.
> 
> We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> 
> <BR clear="all">
> 
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
> 
> <BR clear="all">
> 
> <HR noshade size="1px">
> 
> <PRE>
> 
> Generated by cloudfront (CloudFront)
> 
> Request ID: hCGCME-KFVmCkXCoQb6rb7jvBh6EE9p3iVvv6H15TGF6W9td9IUoQQ==
> 
> </PRE>
> 
> <ADDRESS>
> 
> </ADDRESS>
> 
> </BODY></HTML>]
> 
> ```
> 
> 
> 
> Looks like their Cloudfront config is blocking all requests from Google services

**Comment by akshay6690** [comment]
🙌🏿
